apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: validator4-ambassador-job
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: validator4-ambassador-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/generate_ambassador_certs
    sourceRef:
      kind: GitRepository
      name: flux-sau
      namespace: flux-sau
  values:
    metadata:
      name: validator4-ambassador-job
      namespace: supplychain-bes
    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: regcred
      pullPolicy: IfNotPresent
    network:
      tmtls: True
    node:
      name: validator4
      clientport: 8888
    vault:
      address: http://a94f258ac51304b63a9bceb42a204cb6-2100507752.eu-west-1.elb.amazonaws.com:20002
      secretengine: secretsv2
      authpath: besusupplychain
      rootcasecret: secretsv2/data/supplychain-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: secretsv2/data/supplychain-bes/crypto/validator4/tls
      role: vault-role
      serviceaccountname: vault-auth
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: validator4.bes.dev2.aws.blockchaincloudpoc-develop.com
      domain_name_priv: validator4.supplychain-bes
      domain_name_tessera: validator4-tessera.supplychain-bes
    healthcheck:
      retries: 10
      sleepTimeAfterError: 2
