apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carriers-ambassador-job
  namespace: carriers-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carriers-ambassador-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/generate_ambassador_certs
    sourceRef:
      kind: GitRepository
      name: flux-sau
      namespace: flux-sau
  values:
    metadata:
      name: carriers-ambassador-job
      namespace: carriers-bes
    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: regcred
      pullPolicy: IfNotPresent
    network:
      tmtls: True
    node:
      name: carriers
      clientport: 8888
    vault:
      address: http://a097b80b62b4d4312aca282e211677c9-1359170190.eu-west-1.elb.amazonaws.com:20002
      secretengine: secretsv2
      authpath: besucarriers
      rootcasecret: secretsv2/data/carriers-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: secretsv2/data/carriers-bes/crypto/carriers/tls
      role: vault-role
      serviceaccountname: vault-auth
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: carriers.bes.dev2.aws.blockchaincloudpoc-develop.com
      domain_name_priv: carriers.carriers-bes
      domain_name_tessera: carriers-tessera.carriers-bes
    healthcheck:
      retries: 10
      sleepTimeAfterError: 2
