apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carriers-tessera-job
  namespace: carriers-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carriers-tessera-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/tessera_key_mgmt
    sourceRef:
      kind: GitRepository
      name: flux-sau
      namespace: flux-sau
  values:
    metadata:
      name: carriers-tessera-job
      namespace: carriers-bes
    peer:
      name: carriers
    image:
      repository: quorumengineering/tessera:hashicorp-21.7.3
      pullSecret: regcred
      pullPolicy: IfNotPresent
      alpineutils: ghcr.io/hyperledger/bevel-alpine-ext:latest
    vault:
      address: http://a94f258ac51304b63a9bceb42a204cb6-2100507752.eu-west-1.elb.amazonaws.com:20002
      secretengine: secretsv2
      authpath: besucarriers
      role: vault-role
      keyprefix: carriers-bes/crypto
      serviceaccountname: vault-auth
      tmprefix: secretsv2/data/carriers-bes/crypto
