apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrierscarriersmember-node
  namespace: carriers-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrierscarriersmember-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_besu
    sourceRef:
      kind: GitRepository
      name: flux-sau
      namespace: flux-sau
  values:
    metadata:
      namespace: carriers-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://83b19488f38eb26268904ebaf47f5289ba399879fabf0c246200e40f6ddae6d3ce302171c0de1d711d1dea9d3a56f3658d0a36ada475dda449401f3a7f66fe5f@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15010"
      - "enode://fe4882ca673e046e0bb5703594855951aff517782ee364465cc3c60a8b03dbd18cefad87b47c2cf77abfe5d69b560950c8388342f90d0c5972254435b699bc1c@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15012"
      - "enode://8c239def87ff8f59cdf709e755e230925392e1a0ab151881f83baf3ca620a2ea13af9aa163c243a57df5b51d91257e9a8c8eaff9178cca0f2315e3124d84b5a7@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15014"
      - "enode://a5ad8caa9135c650fe2dcc6a68ccdafd1d036c2d4fdb35aa2f91e836da6a2b8aa956363451560313e3a72882a3c05d436387ba2b24973d6c4b1bbb26ca80eef6@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15016"
      - "enode://577e147fc42cca7d33675d01b22fc1c73beb360745bcd7ce9212a74827677515529b2c2e4e9f593b064974b4563798bc9144fe346e8463fc785715731506c606@carriers.bes.dev2.aws.blockchaincloudpoc-develop.com:15018"

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
    proxy:
      provider: ambassador
      external_url: carriers.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15018
      rpc: 15019

    images:
      node: hyperledger/besu:21.10.6
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: carriers
      consensus: ibft
      subject: O=Carriers,OU=Carriers,L=51.50/-0.13/London,C=GB
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    tm:
      type: tessera
      tls: True
      url: "https://carriers-tessera.carriers-bes:8888"

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://a097b80b62b4d4312aca282e211677c9-1359170190.eu-west-1.elb.amazonaws.com:20002
      secretprefix: secretsv2/data/carriers-bes/crypto/carriers
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besucarriers

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDMxOGFjODE3OTkxNDNhNzk2ZjRiNTk1ZTI3ZTQwZTljZTNiNWVlYjg5NDdlMzdhMDFjNjg2MTJlNmJiYjg1NzUwZjUwMmQ3OWI4YmZiZmJmZTY5NDg0NDFmZWE1ZTg3MWExOTFlYTNjNTQ5N2RmMTRjM2FmNmZiY2ZiNjQ5NDM2NjI3ZmRlMjVlNzdlYzQ5Njc1YThmMjAxYzFhN2ExODg5ZWYxNGQ4MDg0MDAwMDAwMDBjMCIKfQ==

 
