apiVersion:  helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrierstessera
  namespace: carriers-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrierstessera
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_tessera
    sourceRef:
      kind: GitRepository
      name: flux-sau
      namespace: flux-sau
  values:
    replicaCount: 1
    metadata:
      namespace: carriers-bes
      labels:
    images:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      tessera: quorumengineering/tessera:hashicorp-21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    tessera:
      name: carriers-tessera
      dbname: demodb
      dburl: "jdbc:mysql://carriers-tessera:3306/demodb"
      dbusername: demouser
      tls: "STRICT"
      url: "https://carriers.bes.dev2.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "https://carriers-tessera:8888"
      othernodes:
        - url: https://carriers.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://manufacturers.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://stores.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://warehouses.dev2.aws.blockchaincloudpoc-develop.com
      trust: "TOFU"

      servicetype: ClusterIP
      ports:
        tm: 443
        db: 3306
        client: 8888
      mountPath: /etc/tessera/data
      ambassadorSecret: carriers-ambassador-certs
    vault:
      address: http://a097b80b62b4d4312aca282e211677c9-1359170190.eu-west-1.elb.amazonaws.com:20002
      secretengine: secretsv2
      tmsecretpath: carriers-bes/crypto/carriers/tm
      secretprefix: secretsv2/data/carriers-bes/crypto/carriers
      serviceaccountname: vault-auth
      keyname: credentials
      tm_keyname: tm
      tlsdir: tls
      role: vault-role
      authpath: besucarriers
    proxy:
      provider: "ambassador"
      external_url: carriers.bes.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 443
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
