apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychainvalidator1validator-node
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator1validator-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_validator
    sourceRef:
      kind: GitRepository
      name: flux-sau
      namespace: flux-sau
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://5c77469e34fd4f1196ce0d45d9cecbddb94d2c3738fa3d0e13c75388b9a9668c37e8e05b19c5b2750c5cf0f86207b356d4267ae7f618264504fe05c019b6da22@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15010"
      - "enode://bd13b345a54bf97b9f143dfe70fea41706dd013cf83d3426001140e9597c9bb4d72cf1c995bae71880c968d2e23329f515fb1c9a0ee6f2374f9b3e9edbb7bf3a@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15012"
      - "enode://946e3911f3f745ec6fefed3116c1336169490e0dbd8b445aec122434a92997b08c83cb0cf29735e712c718da9f3a8dca74b3352a454d661a648013d06582146a@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15014"
      - "enode://4c8d75c77d49a465adcd682d01c8655519c21467a906fb5f0c87aeb10bd370e7c717f4b6fcec2415dd5c5a05932e3818bb5fb774b4ef67b8594a1963d2a591c7@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15016"
      - "enode://401e8e210e38fe8304439392bc228f4d1bd3647bed7296404760ec770f8659de380f2511afed74db4705558fdfae42afb3e9be0270a4f79b2693d78e66e1d801@carriers.bes.dev2.aws.blockchaincloudpoc-develop.com:15018"

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
    proxy:
      provider: ambassador
      external_url: supplychain.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15010
      rpc: 15011

    images:
      node: hyperledger/besu:21.10.6
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: validator1
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://a94f258ac51304b63a9bceb42a204cb6-2100507752.eu-west-1.elb.amazonaws.com:20002
      secretprefix: secretsv2/data/supplychain-bes/crypto/validator1
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGFiNDA1MTQyYzhiNTkzMzA2YTQ0YmYyZWMyOGUyN2Y3OTViMTE1YmI5NDhjYjM1Y2ZlZTBhZDRlOWU1NTcyY2NlZGEwMDg4ZTcxZjFlNzMwYzc5NDc2MzJlNDZlYTczZTYwYmUxNjUxZGQ3NDU2Mjg0M2Y0NTE5ZTc2MDI5NDBiZDhiNGVkNjM4ZDc1N2NjMDc0NzU1MDIwYmY0OTk0YWU3MGQ0OTE4MDg0MDAwMDAwMDBjMCIKfQ==
