apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychainvalidator3validator-node
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator3validator-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_validator
    sourceRef:
      kind: GitRepository
      name: flux-sau
      namespace: flux-sau
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://df71c6b73e81418b26d4923fa5926c32f7d1d104f0bc718a3bd2026ef2b872b0c2e96ed80ceb5385f6b7cb8daaa264d54b44160b50d12c375bf7372135ec5a3c@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15010"
      - "enode://5ea58f67e62208e6a1d4d8c842ffed98cd5897e9294ba18a684d086c29731b3b165ec6c193c5c6f13cbd4ee76213bbf3de9270accdce0e16ce9246d3aebe9f36@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15012"
      - "enode://f0e9e48ba170918552cc0f72791ba6011051105101813171e16ab8d3ddcf155e2b95d8c95f788d774a0f550e53fbe15bf8ef66799b62f83ed70ab6ff8529f819@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15014"
      - "enode://8fe1b4ade1ca309f1d24bb6d2ddb81146f74ebfeefd3574329db06fa25d1ac48668d8033a6e01ba4964671e97649fa7a513a4f727aef15607772224f5a0838c3@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15016"
      - "enode://c160abb3d27644b8c89f2b317f146330ed6537ba805f063b2e82291db98ec240b2e49fd29d480cc479e25847413f4d28c3dda022de576af2b2f6b6f62897efd7@carriers.bes.dev2.aws.blockchaincloudpoc-develop.com:15018"

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
    proxy:
      provider: ambassador
      external_url: supplychain.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15014
      rpc: 15015

    images:
      node: hyperledger/besu:21.10.6
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: validator3
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://a94f258ac51304b63a9bceb42a204cb6-2100507752.eu-west-1.elb.amazonaws.com:20002
      secretprefix: secretsv2/data/supplychain-bes/crypto/validator3
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDdmNjliZjBhNDMzM2ZkNzEyY2I0ZDMzZWI5ZGNiNjA5MzY0YzczOTI5NDVkZWQyZjk2ZGY5Y2ZjNDg2NjczOWZmYzJhNTQ4MzBiMGI3MmE2MTU5NDgwOWMwY2Q0ZGE2MDI3OTM3NTBkMTEyMDRhOTUwY2MxNTU1ZGY0NzM5NDI2M2I0MjgyYWM0MzAxNDY4ZTg1M2Y1ODcxZTBiNzg4ZTdkZmU4ZjE4MDg0MDAwMDAwMDBjMCIKfQ==
